Capstone/PickUpSports/PickUpSports/Models/DatabaseModels/BusinessHours.cs
using System;

namespace PickUpSports.Models.DatabaseModels
{
    public class BusinessHours
    {
        public int BusinessHoursId { get; set; }

        public int DayOfWeek { get; set; }

        public TimeSpan OpenTime { get; set; }

        public TimeSpan CloseTime { get; set; }

        public int VenueId { get; set; }
    }
}

Capstone/PickUpSports/PickUpSports/Models/DatabaseModels/Game.cs
using System;

namespace PickUpSports.Models.DatabaseModels
{
    public class Game
    {
        public int GameId { get; set; }

        public DateTime StartTime { get; set; }

        public DateTime EndTime { get; set; }
        
        public int VenueId { get; set; }

        public int SportId { get; set; }

        public int? ContactId { get; set; }

        public int GameStatusId { get; set; }
    }
}

Capstone/PickUpSports/PickUpSports/Models/ViewModel/BusinessHoursViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace PickUpSports.Models.ViewModel
{
    public class BusinessHoursViewModel
    {
        public string DayOfWeek { get; set; }

        public string OpenTime { get; set; }

        public string CloseTime { get; set; }
    }
}

Capstone/PickUpSports/PickUpSports/Models/ViewModel/GameController/CreateGameViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PickUpSports.Models.ViewModel.GameController
{
    public class CreateGameViewModel
    {
        [Required]
        [DisplayName("Pick a start and finish time (must start and end on same date):")]
        public string DateRange { get; set; }

        [Required]
        [DisplayName("Venue")]
        public int VenueId { get; set; }

        [Required]
        [DisplayName("Sport")]
        public int SportId { get; set; }
    }
}

Capstone/PickUpSports/PickUpSports/Models/ViewModel/GameController/EditGameViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PickUpSports.Models.ViewModel.GameController
{
    public class EditGameViewModel
    {
        public int GameId { get; set; }

        public int ContactId { get; set; }

        public int VenueId { get; set; }

        public int SportId { get; set; }

        public int GameStatusId { get; set; }

        [Required]
        [DisplayName("Venue:")]
        public string Venue { get; set; }

        [Required]
        [DisplayName("Sport:")]
        public string Sport { get; set; }

        [Required]
        [DisplayName("Status:")]
        public string Status { get; set; }

        [Required]
        [DisplayName("Pick a start and finish time (must start and end on same date):")]
        public string DateRange { get; set; }

        public string StartTime { get; set; }
    }
}

Capstone/PickUpSports/PickUpSports/Models/ViewModel/GameController/GameListViewModel.cs
using System;

namespace PickUpSports.Models.ViewModel.GameController
{
    public class GameListViewModel
    {
        public int? ContactId { get; set; }

        public string ContactName { get; set; }

        public int GameId { get; set; }

        public int? VenueId { get; set; }

        public string Venue { get; set; }

        public string Sport { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

          
        public string GameStatus { get; set; }
    }
}

Capstone/PickUpSports/PickUpSports/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PickUpSports.Interface;
using PickUpSports.Models.DatabaseModels;
using PickUpSports.Models.Enums;
using PickUpSports.Models.ViewModel.ContactController;
using PickUpSports.Models.ViewModel.GameController;

namespace PickUpSports.Controllers
{
    [Authorize]
    public class ContactController : Controller
    {
        private readonly IContactService _contactService;
        private readonly IGameService _gameService;
        private readonly IVenueService _venueService;
        private readonly IVenueOwnerService _venueOwnerService;

        public ContactController(IContactService contactService, IGameService gameService, IVenueService venueService, IVenueOwnerService venueOwnerService)
        {
            _contactService = contactService;
            _gameService = gameService;
            _venueService = venueService;
            _venueOwnerService = venueOwnerService;
        }
        
        /*
         * User's internal profile that only they have access to
         */
        public ActionResult Details()
        {
            string userEmail = User.Identity.GetUserName();

            // First check if venue owner and route to correct profile if so
            bool isVenueOwner = _venueOwnerService.IsVenueOwner(userEmail);
            if (isVenueOwner)
            {
                var owner = _venueOwnerService.GetVenueOwnerByEmail(userEmail);
                return RedirectToAction("Detail", "VenueOwner", new {id = owner.VenueOwnerId});
            }

            Contact contact = _contactService.GetContactByEmail(userEmail);
            
            return View(contact);
        }

        /*
         * Route user to page to edit their account details
         */
        public ActionResult Edit()
        {
            // Get logged in user
            string email = User.Identity.GetUserName();
            Contact contact = _contactService.GetContactByEmail(email);
            if (contact == null) return HttpNotFound();

            ViewBag.States = PopulateStatesDropdown();
            
            EditContactViewModel model = new EditContactViewModel
            {
                ContactId = contact.ContactId,
                Username = contact.Username,
                FirstName = contact.FirstName,
                LastName = contact.LastName,
                Email = contact.Email,
                PhoneNumber = contact.PhoneNumber,
                Address1 = contact.Address1,
                Address2 = contact.Address2,
                City = contact.City,
                State = contact.State,
                ZipCode = contact.ZipCode,
                HasPublicProfile = contact.HasPublicProfile
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditContactViewModel model)
        {
            if (ModelState.IsValid) return View(model);
            Contact existing = _contactService.GetContactById(model.ContactId);

            existing.FirstName = model.FirstName;
            existing.LastName = model.LastName;
            existing.PhoneNumber = model.PhoneNumber;
            existing.Address1 = model.Address1;
            existing.Address2 = model.Address2;
            existing.City = model.City;
            existing.State = model.State;
            existing.ZipCode = model.ZipCode;
            existing.HasPublicProfile = model.HasPublicProfile;

            _contactService.EditContact(existing);

            return RedirectToAction("Details");
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(EditContactViewModel model)
        {
            return RedirectToAction("RemoveAccount", "Account", new { id = model.ContactId});
        }

        /**
         * Endpoint that routes to public profile view. Should take in a Contact ID 
         */
        [HttpGet]
        public ActionResult PlayerProfile(int id)
        {
            var model = new ProfileViewModel();
            var contact = _contactService.GetContactById(id);
            if (contact == null) throw new ArgumentNullException($"Contact ID {id} does not exist.");

            model.Username = contact.Username;
            model.ContactId = contact.ContactId;
            model.UserAllowsPublicProfile = contact.HasPublicProfile;
            return View(model);
        }

        public ActionResult GetSportPreferences(int contactId, bool isPublicProfileView)
        {
            var model = new SportPreferenceViewModel
            {
                ContactId = contactId
            };

            model.IsPublicProfileView = isPublicProfileView;

            var results = _contactService.GetUserSportPreferences(contactId);
            if (results == null) return PartialView("../SportPreferences/_SportPreferences", model);

            model.SportName = results;
            return PartialView("../SportPreferences/_SportPreferences", model);
        }

        public ActionResult GetTimePreferences(int contactId, bool isPublicProfileView)
        {
            var model = new TimePreferenceListViewModel
            {
                ContactId = contactId,
                TimePreferences = new List<TimePreferenceViewModel>()           
            };

            model.IsPublicProfileView = isPublicProfileView;

            var timePreferences = _contactService.GetUserTimePreferences(contactId);
            if (timePreferences == null) return PartialView("../TimePreferences/_TimePreferences", model);

            foreach (var timePreference in timePreferences)
            {
                model.TimePreferences.Add(new TimePreferenceViewModel
                {
                    DayOfWeek = (DayOfWeek) timePreference.DayOfWeek,
                    BeginTime = timePreference.BeginTime,
                    EndTime = timePreference.EndTime
                });
            }

            return PartialView("../TimePreferences/_TimePreferences", model);
        }

        public ActionResult GetGamesStartedByUser(int contactId, bool isPublicProfileView)
        {
            var model = new GameProfileViewModel();
            model.IsPublicProfileView = isPublicProfileView;
            model.ContactId = contactId;

            var games = _gameService.GetCurrentOrderedGamesByContactId(contactId);
            if (games==null) return PartialView("../Game/_GamesUserCreated", model);

            model.Games = new List<GameListViewModel>();

            foreach (var game in games)
            {
                var gameToAdd = new GameListViewModel
                {
                    EndDate = game.EndTime,
                    GameId = game.GameId,
                    GameStatus = ((GameStatusEnum) game.GameStatusId).ToString(),
                    Sport = _gameService.GetSportNameById(game.SportId),
                    StartDate = game.StartTime,
                    Venue = _venueService.GetVenueNameById(game.VenueId),
                    VenueId = game.VenueId
                };

                if (game.ContactId != null)
                {
                    gameToAdd.ContactId = game.ContactId;
                    gameToAdd.ContactName = _contactService.GetContactById(game.ContactId).Username;
                }

                model.Games.Add(gameToAdd);
            }

            return PartialView("../Game/_GamesUserCreated", model);
        }

        public ActionResult GetGamesUserJoined(int contactId, bool isPublicProfileView)
        {
            var model = new GameProfileViewModel();
            model.IsPublicProfileView = isPublicProfileView;
            model.ContactId = contactId;

            var pickUpGames = _gameService.GetPickUpGamesByContactId(contactId);
            if (pickUpGames == null) return PartialView("../Game/_GamesUserJoined", model);

            model.Games = new List<GameListViewModel>();

            foreach (var pickUpGame in pickUpGames)
            {
                var game = _gameService.GetGameById(pickUpGame.GameId);

                // Do not add game to list if time passed
                if (game.EndTime < DateTime.Today.AddDays(-1)) continue;

                // Do not add if user is the creator of game
                if (game.ContactId == contactId) continue;

                var gameToAdd = new GameListViewModel
                {
                    EndDate = game.EndTime,
                    GameId = game.GameId,
                    GameStatus = ((GameStatusEnum)game.GameStatusId).ToString(),
                    Sport = _gameService.GetSportNameById(game.SportId),
                    StartDate = game.StartTime,
                    Venue = _venueService.GetVenueNameById(game.VenueId),
                    VenueId = game.VenueId
                };

                if (game.ContactId != null)
                {
                    gameToAdd.ContactId = game.ContactId;
                    gameToAdd.ContactName = _contactService.GetContactById(game.ContactId).Username;
                }

                model.Games.Add(gameToAdd);
            }

            model.Games = model.Games.OrderBy(x => x.StartDate).ToList();
            return PartialView("../Game/_GamesUserJoined", model);
        }

        public ActionResult GetGamesRejected(int contactId, bool isPublicProfileView)
        {
            var model = new GameProfileViewModel();
            model.IsPublicProfileView = isPublicProfileView;
            model.ContactId = contactId;

            List<Game> gameList = _gameService.GetAllGamesByContactId(model.ContactId);

            if(gameList == null) return PartialView("../Game/_GetGamesRejected", model);

            model.Games = new List<GameListViewModel>();

            foreach (var game in gameList)

Capstone/PickUpSports/PickUpSports/Views/Game/CreateGame.cshtml
@model PickUpSports.Models.ViewModel.GameController.CreateGameViewModel

@{
    ViewBag.Title = "Start a New Game";
}

<link rel="stylesheet" type="text/css" href="../../Content/daterangepicker.css" />
<link rel="stylesheet" type="text/css" href="../../Content/Site.css" />

@section Scripts
{
    <script src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script src="../../Scripts/gameView.js"></script>
}

@using (Html.BeginForm("CreateGame", "Game", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <div class="form-box">
                <h2>Start a New Game</h2>
                <form role="form" id="game-form">
                    @if (!ViewData.ModelState.IsValid)
                    {
                        <div class="row">
                            <div class="col-md-12">
                                @Html.ValidationSummary(false, null, new { @class = "text-danger" })

                            </div>
                        </div>
                    }

                    <!-- Venue field -->
                    <div class="form-group">
                        @Html.DropDownListFor(
                            x => x.VenueId,
                            new SelectList(ViewBag.Venues, "Key", "Value"),
                            "Select a Venue",
                            new {@class = "form-control", @onchange = "getVenueBusinessHours()"})
                    </div>

                    <div id="hours">
                        <div class="form-group">
                            @*Partial view updated by ajax call in gameView.js*@
                        </div>
                    </div>

                    <!-- Sport field -->
                    <div class="form-group" style="padding-top: 20px">
                        @Html.DropDownListFor(
                            x => x.SportId,
                            new SelectList(ViewBag.Sports, "Key", "Value"),
                            "Select a Sport",
                            new {@class = "form-control"})
                    </div>

                    <!-- Date field -->
                    <div class="form-group" style="padding-top: 20px">
                        @Html.DisplayNameFor(x => x.DateRange)
                        @Html.EditorFor(x => x.DateRange, new { htmlAttributes = new { @class = "form-control", name = "datetimes", @id = "datetimes" } })
                    </div>

                    <div class="form-group">
                        <center>
                            <button type="submit" class="btn btn-default">Create Your Game</button>
                        </center>
                    </div>

                    @if (ViewBag.GameCreated != null && ViewBag.GameCreated)
                    {
                        <div class="form-group">
                            <center>
                                <p><span class="glyphicon glyphicon-ok"></span> Game created successfully!</p>
                            </center>
                        </div>
                    }
                </form>
            </div>
        </div>
    </div>
}

Capstone/PickUpSports/PickUpSports/Views/Game/EditGame.cshtml
@model PickUpSports.Models.ViewModel.GameController.EditGameViewModel
@{
    ViewBag.Title = "Edit Your Game";
}

<link rel="stylesheet" type="text/css" href="../../Content/daterangepicker.css" />
<link rel="stylesheet" type="text/css" href="../../Content/Site.css" />

@section Scripts
{
    <script src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script src="../../Scripts/gameEdit.js"></script>
}

@using (Html.BeginForm("EditGame", "Game", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="row">
            <div class="well well-sm">

                <fieldset>
                    @Html.HiddenFor(model => model.ContactId)
                    @Html.HiddenFor(model => model.GameId)
                    @Html.HiddenFor(model => model.VenueId)
                    @Html.HiddenFor(model => model.SportId)
                    <h4>Edit Game Detail</h4>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Venue)
                        @Html.DropDownList("Venue", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Status)
                        @Html.DropDownList("Status", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Sport)
                        @Html.DropDownList("Sport", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group" style="padding-top: 20px">
                        @Html.DisplayNameFor(x => x.DateRange)
                        @Html.EditorFor(x => x.DateRange, new { htmlAttributes = new { @class = "form-control", name = "datetimes", @id = "datetimes" } })
                    </div>
                    @if (!ViewData.ModelState.IsValid)
                    {
                        <div class="row">
                            <div class="col-md-12">
                                @Html.ValidationSummary(false, null, new { @class = "text-danger" })

                            </div>
                        </div>
                    }

                    <button type="submit" id="submit" class="btn btn-primary">Edit Information</button>


                </fieldset>

            </div>


        </div>


    </div>

}

Capstone/PickUpSports/PickUpSports/Views/Game/GameDetails.cshtml
@using PickUpSports.Models.Enums
@model PickUpSports.Models.ViewModel.GameController.ViewGameViewModel
@{
    ViewBag.Title = "Game Details";
}
@section Scripts
{
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="../../Scripts/pickUpGameView.js"></script>
}

<head>
    <link href="@Url.Content("/Content/playerTable.css")" rel="stylesheet" type="text/css" />
</head>


<div class="container">
    <div class="row">
        <div class="well">
            <fieldset>
                <h4>Game Detail</h4>
                <div class="form-group">
                    @Html.LabelFor(model => model.ContactName)
                    @if (Model.ContactId == null)
                    {
                        <html>
                        User that created this game no longer has an account.
                        </html>
                    }
                    else
                    {
                        <html>
                        @Html.ActionLink(Model.ContactName, "PlayerProfile", "Contact", new {id = Model.ContactId}, null)
                        </html>
                    }     
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Venue)
                    @Html.DisplayFor(model => model.Venue)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Status)
                    @Html.DisplayFor(model => model.Status)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Sport)
                    @Html.DisplayFor(model => model.Sport)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate)
                    @Html.DisplayFor(model => model.StartDate)
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.EndDate)
                    @Html.DisplayFor(model => model.EndDate)
                </div>
                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="row">
                        <div class="col-md-12">
                            @Html.ValidationSummary(false, null, new {@class = "text-danger", @id ="error-msg"})

                        </div>
                    </div>
                }

                <center>
                    <p>
                        @using (Html.BeginForm("GameDetails", "Game", FormMethod.Post))
                        {
                            @Html.HiddenFor(model => model.GameId)
                            @Html.HiddenFor(model => model.ContactId)
                            @Html.HiddenFor(model => model.PickUpGameId)
                            if (Model.IsVenueOwner)
                            {
                                if (Model.Status == "Rejected")
                                {
                                    <input type="submit" name="button" class="btn btn-default" id="submit" value="Accept Game"/>
                                }

                                if (Model.Status == "Open" || Model.Status == "Accepted")
                                {
                                    <input type="submit" name="button" class="btn btn-default" id="submit" value="Reject Game"/>
                                }
                            }
                            else if(Model.Status == "Rejected")
                            {
                                <p>The game is rejected, you can't join this game</p>
                            }
                            else
                            {
                                // User created game so shouldn't have option to leave or join, just edit
                                if (Model.IsCreatorOfGame)
                                {
                                    <input type="button" class="btn btn-default" value="Edit Information" id="submit" onclick="location.href = '@Url.Action("EditGame", "Game", new {id = Model.GameId})'" />
                                }
                                // User is not creator but they already joined this game, only show leave button
                                else if(Model.IsAlreadyJoined)
                                {
                                    <input type="submit" name="button" value="Leave Game" id="submit"  class="btn btn-default" />
                                }
                                // User is not creator and is not joined, only show joined game option
                                else
                                {
                                    <input type="submit" name="button" value="Join Game" id="submit"  class="btn btn-default" />
                                }
                            }


                        }

                    </p>
                </center>

            </fieldset>
            
        </div>


    </div>
    <div id="myList">

    </div>
    
    @if(Model.Status != "Rejected")
    {
        <input type="button" class="btn btn-default" value="Invite a friend" id="submit" onclick="location.href = '@Url.Action("FriendInvite", "Friends", new {gameId = Model.GameId})'" />

    }
</div>

Capstone/PickUpSports/PickUpSports/Views/Game/GameList.cshtml
@model List<PickUpSports.Models.ViewModel.GameController.GameListViewModel>

<link rel="stylesheet" type="text/css" href="../../Content/daterangepicker.css"/>
<link rel="stylesheet" type="text/css" href="../../Content/Site.css"/>

@section Scripts
{
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="../../Scripts/searchVenues.js"></script>
    <script src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script src="../../Scripts/gameView.js"></script>
}

<div class="row">
<div class="form-box">
    <h4>Open Games</h4>
    <br />
    <h5 style="color: white">Sort by one of the following filters:</h5>
    <div class="col-md-6">
        <h5>By Venue</h5>
        @Html.DropDownList("Venue", null, "Select Venue", new { @class = "form-control", id = "venueList", onchange = "getGamesByVenue()" })
    </div>
    <div class="col-md-6">

        <h5>By Sport</h5>
        @Html.DropDownList("Sport", null, "Select Sport", new { @class = "form-control", id = "sportList", onchange = "getGamesBySport()" })
    </div>
    <div class="row" style="padding-top: 10px">
        <div class="col-md-12">
            <h5>By Time</h5>
            @Html.Editor("Time Filter", new { htmlAttributes = new { @class = "form-control", name = "datetimes", id = "datetimes" } })
        </div>
    </div>
</div>
</div>
<div class="row" style="padding-top: 30px">
    <ul class="rolldown-list" id="myList">
        <li>

            @foreach (var game in Model)
            {
                <div class="row">
                    @Html.DisplayFor(model => game.Sport) at @Html.DisplayFor(model => game.Venue)
                </div>
                <div class="row">
                    @Html.DisplayFor(model => game.StartDate) to @Html.DisplayFor(model => game.EndDate)
                </div>
                <div class="row">
                    @if (game.ContactId == null)
                    {
                        <html>
                        User that created this game no longer has an account.
                        </html>
                    }
                    else
                    {
                        <html>
                        Game started by @Html.ActionLink(game.ContactName, "PlayerProfile", "Contact", new {id = game.ContactId}, null)
                        </html>
                    }
                </div>


                <div class="row">
                    <br/>@Html.ActionLink("Click here for more details on game", "GameDetails", new {id = game.GameId})
                </div>
                <hr/>
            }
        </li>
    </ul>
</div>

Capstone/PickUpSports/PickUpSports/Views/Game/_GameSearch.cshtml
@model List<PickUpSports.Models.ViewModel.GameController.GameListViewModel>
@{
    ViewBag.Title = "Pick Up Games";
}


<li>
    @if (!ViewData.ModelState.IsValid)
    {
        <div class="row">
            <div class="col-md-12">
                @Html.ValidationSummary(false, null, new {@class = "text-danger", @id ="error-msg"})

            </div>
        </div>
    }
    @if (Model != null)
    {
        foreach (var game in Model)
         {
                 <div class="row">
                     @Html.DisplayFor(model => game.Sport) at @Html.DisplayFor(model => game.Venue)
                 </div>
                 <div class="row">
                     @Html.DisplayFor(model => game.StartDate) to @Html.DisplayFor(model => game.EndDate)
                 </div>
                 <div class="row">
                     Game started by @Html.ActionLink(game.ContactName, "PlayerProfile", "Contact", new {id = game.ContactId}, null)
                 </div>


                 <div class="row">
                     <br/>@Html.ActionLink("Click here for more details on game", "GameDetails", new {id = game.GameId})
                 </div>
             <hr/>
         }
    }
</li>

Capstone/PickUpSports/PickUpSports/Views/Game/_GamesUserJoined.cshtml
@model PickUpSports.Models.ViewModel.ContactController.GameProfileViewModel

@if (Model.Games != null && Model.Games.Count > 0)
{
    <ul class="list-group">
        @foreach (var game in Model.Games)
        {
            <li class="list-group-item">
                <p>
                    @Html.DisplayFor(model => game.Sport) at @Html.ActionLink(game.Venue, "Details", "Venue", new { id = game.VenueId }, null)
                    <br /> @Html.DisplayFor(model => game.StartDate) to @Html.DisplayFor(model => game.EndDate)
                    @if (game.ContactId == null)
                    {
                        <br />
                        <html>
                        User that created this game no longer has an account.
                    </html>
                }
                else
                {
                    <br />
                    <html>
                    Game started by @Html.ActionLink(game.ContactName, "PlayerProfile", "Contact", new { id = game.ContactId }, null)
                </html>
            }
                    <br />Game status: @Html.DisplayFor(model => game.GameStatus)
                </p>
                <br />
                @Html.ActionLink("Click here for more details on game", "GameDetails", "Game", new { id = game.GameId }, null)
            </li>
        }
    </ul>
}
else
{
    if (Model.IsPublicProfileView)
    {
        <h6>This user hasn't joined any games yet.</h6>
    }
    else
    {
        <h6>You have not joined any games yet.</h6>
        @Html.ActionLink("View games to join!", "GameList", "Game", null, null)
    }
}

Capstone/PickUpSports/PickUpSports/Views/Game/_PlayerList.cshtml
@model List<PickUpSports.Models.ViewModel.GameController.PickUpGameViewModel>

<h4 id="warning">@ViewBag.ErrorMsg</h4>
@if (Model == null)
{
<center>
    <h5>No players have joined this game yet.</h5>
</center>
}
else
{
    <table class="table rwd-table" id="playerTable">
        <tr>
            <th>@Html.DisplayName("Players signed up for this game:")</th>
        </tr>


        @foreach (var player in Model)
        {
            @Html.HiddenFor(model => player.GameId)
            @Html.HiddenFor(model => player.PickUpGameId)

            <tr>
                <td>
                    @Html.ActionLink(player.Username, "PlayerProfile", "Contact", new { id = player.ContactId }, null)
            </td>
        </tr>
    }
    </table>
}