Capstone/PickUpSports/PickUpSports/Controllers/HomeController.cs
using System.Net.Mail;
using System.Web.Mvc;
using PickUpSports.Interface;
using PickUpSports.Models.ViewModel.HomeController;

namespace PickUpSports.Controllers
{
    public class HomeController : Controller
    {
        private readonly IGMailService _gmailer;

        public HomeController(IGMailService gmailer)
        {
            _gmailer = gmailer;
        }

        [RequireHttps]
        public ActionResult Index()
        {
            return View();
        }

        [System.Web.Mvc.Authorize]
        public ActionResult Chat()
        {
            return View();
        }

        public ActionResult AboutUs()
        {
            return View();
        }

        public ActionResult Contact(ContactUsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.SubmitEmailSent = false;
                return View("AboutUs");
            }

            // Send email to Scrum Lords for approval
            var email = new MailMessage();
            email.To.Add(_gmailer.GetEmailAddress());
            email.From = new MailAddress(model.Email);
            email.Subject = $"Support inquiry received from {model.Name}.";
            email.Body = $"Received following inquiry from {model.Name}, email address {model.Email}: " + model.Message;
            email.IsBodyHtml = true;

            // Send email and return to view if successful
            if (_gmailer.Send(email))
            {
                ViewBag.SubmitEmailSent = true;
                return View("AboutUs", model);
            }

            // Email could not be sent, display error 
            ViewBag.SubmitEmailSent = false;
            ViewData.ModelState.AddModelError("EmailError", "Unfortunately, your email could not be sent.");
            return View("AboutUs", model);
        }
    } 
}

Capstone/PickUpSports/PickUpSports/Controllers/VenueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PickUpSports.Interface;
using PickUpSports.Models.DatabaseModels;
using PickUpSports.Models.Enums;
using PickUpSports.Models.Extensions;
using PickUpSports.Models.ViewModel;
using PickUpSports.Models.ViewModel.GameController;
using PickUpSports.Models.ViewModel.VenueController;
using PickUpSports.Models.ViewModel.VenueOwnerController;

namespace PickUpSports.Controllers
{
    public class VenueController : Controller
    {
        private readonly IVenueService _venueService;
        private readonly IContactService _contactService;
        private readonly IGameService _gameService;
        private readonly IVenueOwnerService _venueOwnerService;

        public VenueController(IVenueService venueService, 
            IContactService contactService, 
            IGameService gameService,
            IVenueOwnerService venueOwnerService)
        {
            _venueService = venueService;
            _contactService = contactService;
            _gameService = gameService;
            _venueOwnerService = venueOwnerService;
        }
        
        /*
         * Show a list of venues
         */
        public ActionResult Index()
        {
            _venueService.UpdateVenues();

            // Create view model for list of venues
            SearchVenueViewModel model = new SearchVenueViewModel();
            model.Venues = new List<VenueViewModel>();
            List<Venue> venues = _venueService.GetAllVenues();

            foreach (var venue in venues)
            {
                // get location of venue
                Location location = _venueService.GetVenueLocation(venue.VenueId);
                
                // get the rating 
                List<Review> reviews = _venueService.GetVenueReviews(venue.VenueId);

                decimal? avgRating;
                if (reviews.Count > 0)
                {
                    avgRating = (decimal) reviews.Average(r => r.Rating);
                }
                else avgRating = null;


                model.Venues.Add(new VenueViewModel
                {
                    Address1 = venue.Address1,
                    Address2 = venue.Address2,
                    City = venue.City,
                    Name = venue.Name,
                    Phone = venue.Phone,
                    State = venue.State,
                    VenueId = venue.VenueId,
                    ZipCode = venue.ZipCode,
                    AverageRating = avgRating,
                    LatitudeCoord = location.Latitude,
                    LongitudeCoord = location.Longitude,
                });
            }

            return View(model);
        }

        /*
         * Venue search and filter results
         */
        [HttpPost]
        public ActionResult Filter(SearchVenueViewModel model)
        {
            model.Venues = (List<VenueViewModel>) TempData["Venues"];

            // Create new model to send to view
            SearchVenueViewModel viewModel = new SearchVenueViewModel();
            viewModel.Venues = new List<VenueViewModel>();

            if (model.Venues.Count == 0)
            {
                ViewBag.Error = "No results to filter. Please click \"Reset all filters\"";
                return View("Index", viewModel);
            }

            // User entered a search string
            if (!string.IsNullOrEmpty(model.Search))
            {
                // Search venue names and cities
                viewModel.Venues.AddRange(model.Venues.Where(x => x.Name.CaseInsensitiveContains(model.Search)).ToList());
                viewModel.Venues.AddRange(model.Venues.Where(x => x.City.CaseInsensitiveContains(model.Search)));
                
                // Get first venue on list and assign coordinates to map center
                var firstVenue = viewModel.Venues.FirstOrDefault();
                if (firstVenue != null)
                {
                    viewModel.CurrentLatitude = firstVenue.LatitudeCoord;
                    viewModel.CurrentLongitude = firstVenue.LongitudeCoord;
                }
            }

            if (!string.IsNullOrEmpty(model.Filter))
            {
                // User chose to sort by rating
                if (model.Filter.Equals("Rating"))
                {
                    viewModel.Venues = model.Venues.OrderByDescending(x => x.AverageRating).ToList();

                    if (viewModel.Venues.Count == 0)
                    {
                        ViewBag.Error = "No search results matching given filters";
                    }

                    // Get first venue on list and assign coordinates to map center
                    var firstVenue = viewModel.Venues.FirstOrDefault();
                    if (firstVenue != null)
                    {
                        viewModel.CurrentLatitude = firstVenue.LatitudeCoord;
                        viewModel.CurrentLongitude = firstVenue.LongitudeCoord;
                    }
                }
                // User chose to filter by time
                if (model.Filter.Equals("Time"))
                {
                    //get all the buiness hours for all the venues
                    List<BusinessHours> hours = _venueService.GetAllBusinessHours();

                    //lets wait till time is NOT null
                    if (model.Time != null)
                    {
                        //convert user input string to a TimeSpan
                        TimeSpan hs = TimeSpan.Parse(model.Time);

                        var dayOfWeek = Enum.Parse(typeof(DayOfWeek), model.Day);
                        //First filter out using the days
                        List<BusinessHours> day_available = hours.Where(x => x.DayOfWeek == (int) dayOfWeek).ToList();

                        //Then use that list and filter the closed times
                        List<BusinessHours> closed_from = day_available.Where(x => x.CloseTime >= hs).ToList();

                        //Finally filter the list above and you have the remaning few which maches the days and the closing time
                        List<BusinessHours> open_from = closed_from.Where(x => x.OpenTime <= hs).ToList();

                        //If there are some in the list that matches the user input - else it didnt match
                        if (open_from.Count > 0)
                        {
                            foreach (var businessHour in open_from)
                            {
                                // Only keep venues that are in open_from
                                var venue = model.Venues.FirstOrDefault(x => x.VenueId == businessHour.VenueId);
                                if (venue != null && !viewModel.Venues.Contains(venue)) viewModel.Venues.Add(venue);
                            }
                        }
                    }

                    // Get first venue on list and assign coordinates to map center
                    var firstVenue = viewModel.Venues.FirstOrDefault();
                    if (firstVenue != null)
                    {
                        viewModel.CurrentLatitude = firstVenue.LatitudeCoord;
                        viewModel.CurrentLongitude = firstVenue.LongitudeCoord;
                    }
                }

                // User chose to filter by distance
                if (model.Filter.Equals("Distance"))
                {
                    foreach (var venue in model.Venues)
                    {
                        //get location of venue
                        Location location = _venueService.GetVenueLocation(venue.VenueId);

                        //converted coordinates from strings to doubles
                        double userLat = Convert.ToDouble(model.CurrentLatitude);
                        double userLong = Convert.ToDouble(model.CurrentLongitude);
                        double venLat = Convert.ToDouble(location.Latitude);
                        double venLong = Convert.ToDouble(location.Longitude);

                        //Calculate the distance from user to venue. Method at the bottom
                        venue.Distance = _venueService.CalculateVenueDistance(userLat, userLong, venLat, venLong);
                        viewModel.Venues.Add(venue);
                    }

                    viewModel.Venues = viewModel.Venues.OrderBy(x => x.Distance).ToList();

                    // Get closest venue to user and assign coordinates to map center
                    var closest = viewModel.Venues.First();
                    viewModel.CurrentLatitude = closest.LatitudeCoord;
                    viewModel.CurrentLongitude = closest.LongitudeCoord;

                }
            }
           
            if (viewModel.Venues.Count == 0)
            {
                ViewBag.Error = "No search results matching given filters";
            }

            // Preserve search/filter values
            viewModel.Day = model.Day;
            viewModel.Time = model.Time;
            viewModel.Search = model.Search;

            if (string.IsNullOrEmpty(viewModel.CurrentLatitude))
            {
                viewModel.CurrentLatitude = model.CurrentLatitude;
                viewModel.CurrentLongitude = model.CurrentLongitude;
            }

            model.Venues.Clear();
            return View("Index", viewModel);
        }

        /*
         * Get venue, hours, and review data for single Venue and return to view
         */
        public ActionResult Details(int id)
        {
            // Initializing Owner authentication variable 
            ViewBag.IsOwner = false;

            // Model to be sent to view
            VenueViewModel model = new VenueViewModel();

            // Map venue details
            Venue venue = _venueService.GetVenueById(id);
            model.Address1 = venue.Address1;
            model.Address2 = venue.Address2;

Capstone/PickUpSports/PickUpSports/Views/Home/AboutUs.cshtml
@model PickUpSports.Models.ViewModel.HomeController.ContactUsViewModel

@{
    ViewBag.Title = "About Rec Nexus";
}

<div class="container">
    <div class="row">
        <div class="form-box">
            <h2>Our Vision Statement</h2>
            <p>
                <center>
                    For active individuals who would like to utilize local parks and facilities and engage in sports with other individuals, Nec Rexus is a web application that reintroduces the sense of community and opens doors for available facilities with help from park and venue owners. This application will help users form groups through common sport interests or activity interests and at the same time obtain details and reviews on the facilities where these sports can take place. Unlike other sport grouping applications, our website encourages entities and owners to sign up and keep their venue information up to date and ensure time slots are available for players to provide a seamless and enjoyable experience to those wanting to use their facilities. Our website also allows players to find and interact with others near them with similar sport preferences or who can play at the same times. These features provide an interactive way for players and venues to come together through mutual interests and to get out and play!
                </center>
            </p>
        </div>
    </div>
</div>


<hr/>
@using (Html.BeginForm("Contact", "Home", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <div class="form-box">
                <h2>Contact Us</h2>
                <center>
                    <p>
                        If you see any misinformation on our site, wish to have your facility added,<br />
                        or for any general inquiries, please use the form below to contact us.
                    </p>
                </center>

                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="row">
                        <div class="col-md-12">
                            @Html.ValidationSummary(false, null, new { @class = "text-danger" })

                        </div>
                    </div>
                }

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="text" class="form-control" placeholder="Your Name" name="Name">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="text" class="form-control" placeholder="Email Address" name="Email">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-12">
                            <textarea class="form-control" style="resize:none;" rows="10" placeholder="Questions or comments" name="Message"></textarea>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <center>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </center>
                    </div>
                </div>

                @if (ViewBag.SubmitEmailSent != null && ViewBag.SubmitEmailSent)
                {
                    <div class="form-group">
                        <center>
                            <p><span class="glyphicon glyphicon-ok"></span> Your inquiry has been sent!</p>
                            <p>Please allow 24-48 hours for an administrator to get back to you.</p>
                        </center>
                    </div>
                }
            </div>
        </div>
    </div>
}

Capstone/PickUpSports/PickUpSports/Views/Home/Chat.cshtml
@{
    ViewBag.Title = "Chat";
}

<style type="text/css">
    ul {
        margin: 0;
    }
    ul li {
        padding: 0;
        list-style-type: none;
    }
 </style>

<h2>Chat</h2>

<div>
    <center>Hi @User.Identity.Name! Welcome to Global Channel!</center>
</div>

<div data-bind="visible: isInPrivateChat">
    You are in a private chat with @@<span data-bind="text: privateChatUser"></span>! <a href="#" data-bind="click: exitFromPrivateChat">Exit from private chat?</a>
</div>

<div class="row-fluid">
    <div class="span8 form-search">
        <input type="text" id="txtMsg" class="input-xxlarge" style="color: black" disabled="disabled" />
        <button type="button" id="btnSend" class="btn btn-info" disabled="disabled">Send</button>
        <ul id="messages" data-bind="foreach: messages">
            <li>
                <span class="label label-primary" data-bind="visible: isPrivate">Private</span>
                <strong><span data-bind="text: from"></span>: </strong>
                <span data-bind="text: message"></span>
            </li>
        </ul>
    </div>
    <div class="col-75"></div>
   </div>
<div id="users" class="span2">
    <ul data-bind="foreach: users">
        <li data-bind="click: setAsPrivateChat, css: { privateChatUser: isPrivateChatUser }">
            <span data-bind="text: name"></span>
        </li>
    </ul>
</div>
@section scripts {

    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/ChatInit.js"></script>
}

Capstone/PickUpSports/PickUpSports/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="jumbo">
    <img src="../../Content/header.jpg" style="height: 700px; width: 100%; opacity: 0.8; max-width: 100%;" />
    <div class="centered">Bringing communities <br />together through sports</div>
</div>



<div class="container">
    
    <div class="row" style="padding-top:20px">
        <div class="col-md-4">
            <center>
                <img src="../../Content/images/sportIcon.png" style="height: 50px; width: 50px; color: #F18F01" />
                <hr/>
                <p>
                    View all games that other players <br />in your area have started!
                </p>
                <p><a href="@Url.Action("GameList", "Game")">View Games</a></p>
            </center>
        </div>
        <div class="col-md-4">
            <center>
                <img src="../../Content/images/startGame.png" style="height: 50px; width: 50px;" />
                <hr/>
                <p>
                    Don't see a game you like? <br/>Start your own!
                </p>
                <p><a href="@Url.Action("CreateGame", "Game")">Start Game</a></p>
            </center>
        </div>
        <div class="col-md-4">
            <center>
                <img src="../../Content/images/venues.png" style="height: 50px; width: 50px;" />
                <hr/>
                <p>
                    View local parks and venues <br/>that are in your area!
                </p>
                <p><a href="@Url.Action("Index", "Venue")">View Venues</a></p>
            </center>
        </div>
    </div>
</div>

<style>
    /* Container holding the image and the text */
    .jumbo {
        position: relative;
        text-align: center;
        color: white;
    }

    /* Centered text */
    .centered {
        position: absolute;
        top: 50%;
        left: 50%;
        font-weight: bold;
        text-align: center;
        font-size: 36pt;
        text-transform: uppercase;
        text-shadow: -2px -2px 0 #000, 1px -2px 0 #000, -2px 2px 0 #000, 2px 2px 0 #000;
        transform: translate(-50%, -50%);
        max-width: 75%;
    }
</style>