Capstone/PickUpSports/PickUpSports/Models/DatabaseModels/VenueOwner.cs
using System;

namespace PickUpSports.Models.DatabaseModels
{
    public class VenueOwner
    {
        public int VenueOwnerId { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }

        public string Phone { get; set; }

        public string CompanyName { get; set; }

        public DateTime SignUpDate { get; set; }

        public int VenueId { get; set; }
    }
}

Capstone/PickUpSports/PickUpSports/Models/ViewModel/VenueOwnerController/VenueOwnerViewModel.cs
using System;

namespace PickUpSports.Models.ViewModel.VenueOwnerController
{
    public class VenueOwnerViewModel
    {
        public int VenueOwnerId { get; set; }

        public int VenueId { get; set; }

        public string VenueName { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }

        public string PhoneNumber { get; set; }

        public string CompanyName { get; set; }

        public DateTime SignUpDate { get; set; }
    }
}

Capstone/PickUpSports/PickUpSports/Controllers/VenueOwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PickUpSports.Interface;
using PickUpSports.Models;
using PickUpSports.Models.DatabaseModels;
using PickUpSports.Models.Enums;
using PickUpSports.Models.ViewModel.VenueOwnerController;

namespace PickUpSports.Controllers
{
    public class VenueOwnerController : Controller
    {
        private readonly IGMailService _gMailer;
        private readonly IVenueOwnerService _venueOwnerService;
        private readonly IVenueService _venueService;
        private ApplicationUserManager _userManager;
        private readonly IGameService _gameService;
        private readonly IContactService _contactService;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public VenueOwnerController(IGMailService gMailer, 
            IVenueOwnerService venueOwnerService, 
            IVenueService venueService, IGameService gameService, IContactService contactService)
        {
            _gMailer = gMailer;
            _venueOwnerService = venueOwnerService;
            _venueService = venueService;
            _gameService = gameService;
            _contactService = contactService;
        }

        public ActionResult ClaimVenue(int venueId)
        {
            var model = new ClaimVenueFormViewModel();
            model.VenueId = venueId;
            model.VenueName = _venueService.GetVenueNameById(venueId);

            ViewBag.SubmitEmailSent = false;
            return View(model);
        }

        [HttpPost]
        public ActionResult ClaimVenue(ClaimVenueFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.SubmitEmailSent = false;
                return View(model);
            }

            // Send email to Scrum Lords for approval
            var email = new MailMessage();
            email.To.Add(_gMailer.GetEmailAddress());
            email.From = new MailAddress(model.Email);
            email.Subject = $"Received request to claim venue {model.VenueName}.";
            email.Body = $"Received below request to claim venue {model.VenueName}:<br />"
                         + $"Name: {model.FirstName} {model.LastName}<br />"
                         + $"Email: {model.Email}<br />"
                         + $"Phone: {model.PhoneNumber}<br />"
                         + $"Company name (if applicable): {model.CompanyName}<br />"
                         + "Proof of ownership document is attached.";
            email.IsBodyHtml = true;

            var attachment = new Attachment(model.Document.InputStream, model.Document.FileName);
            email.Attachments.Add(attachment);

            // Send email and return to view if successful
            if (_gMailer.Send(email))
            {
                ViewBag.SubmitEmailSent = true;
                return View(model);
            }

            // Email could not be sent, display error 
            ViewBag.SubmitEmailSent = false;
            ViewData.ModelState.AddModelError("EmailError", "Unfortunately, your email could not be sent.");
            return View(model);
        }

        [Authorize(Roles="Admin")]
        public ActionResult GetAllVenuOwners()
        {
            var allOwners = _venueOwnerService.GetAllVenueOwners();
            var model = new List<VenueOwnerViewModel>();

            foreach (var venueOwner in allOwners)
            {
                model.Add(new VenueOwnerViewModel
                {
                    FirstName = venueOwner.FirstName,
                    LastName = venueOwner.LastName,
                    CompanyName = venueOwner.CompanyName,
                    Email = venueOwner.Email,
                    PhoneNumber = venueOwner.Phone,
                    SignUpDate = venueOwner.SignUpDate,
                    VenueName = _venueService.GetVenueNameById(venueOwner.VenueId),
                    VenueOwnerId = venueOwner.VenueOwnerId,
                    VenueId = venueOwner.VenueId
                });
            }

            return PartialView("_ModifyVenueOwners", model);

        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            //Return drop down of the venues
            PopulateDropdownValues();
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Create(CreateVenueOwnerViewModel model)
        {
            PopulateDropdownValues();

            //if model state is invalid return
            if (!ModelState.IsValid)
            {
                PopulateDropdownValues();
                return View(model);
            }

            //Find venue with the view model id
            Venue venue = _venueService.GetVenueById(model.VenueId);

            //If the venue already has an owner, error 
            if (_venueOwnerService.VenueHasOwner(venue))
            {
                ViewData.ModelState.AddModelError("OwnerExists", "There is already an owner for this Venue");
                PopulateDropdownValues();
                return View(model);
            }

            // Adding owner to AspNetUsers table
            var user = new ApplicationUser { UserName = model.Email, Email = model.Email, EmailConfirmed = true};

            var temporaryPassword = System.Web.Configuration.WebConfigurationManager.AppSettings["VenueOwnerTemporaryPassword"];
            var result = UserManager.Create(user, temporaryPassword);
            if (result.Succeeded)
            {
                //Creating new owner with the values from the view
                VenueOwner owner = new VenueOwner
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    Phone = model.PhoneNumber,
                    CompanyName = model.CompanyName,
                    SignUpDate = DateTime.Now,
                    VenueId = venue.VenueId
                };

                //Add the owner to the table, and save changes
                _venueOwnerService.AddVenueOwner(owner);

                // Only admin can create venue owner so return to admin dashboard
                return RedirectToAction("Index", "Admin");
            }
            
            ViewData.ModelState.AddModelError("AddError", "Could not add venue owner.");
            PopulateDropdownValues();
            return View(model);
        }

        [Authorize]
        public ActionResult Detail(int? id)
        {
            //Bool variable for the View: checking if user is venue owner or not
           ViewBag.IsOwner = false;

            //Get the current logged in user - will be implemented in the future when the log in function/ page is complete
            string ownerEmail = User.Identity.GetUserName();

            //Check if current logged in user is the owner
            if (_venueOwnerService.IsVenueOwner(ownerEmail))
            {
                ViewBag.IsOwner = true;

                VenueOwner owner = _venueOwnerService.GetVenueOwnerByEmail(ownerEmail);

                //Create the view model using values of the owner if not null
                CreateVenueOwnerViewModel model = new CreateVenueOwnerViewModel()
                {
                    VenueOwnerId = owner.VenueOwnerId,
                    FirstName = owner.FirstName,
                    LastName = owner.LastName,
                    Email = owner.Email,
                    PhoneNumber = owner.Phone,
                    CompanyName = owner.CompanyName,
                    SignUpDate = owner.SignUpDate,
                    VenueName = _venueService.GetVenueNameById(owner.VenueId),
                    VenueId = owner.VenueId
                };

                //Return it back to the view
                return View(model);
            }
            else
            {
                ViewBag.IsOwner = false;
                VenueOwner owner = _venueOwnerService.GetVenueOwnerById((int) id);

                CreateVenueOwnerViewModel model = new CreateVenueOwnerViewModel()
                {
                    VenueOwnerId = owner.VenueOwnerId,
                    FirstName = owner.FirstName,
                    LastName = owner.LastName,
                    Email = owner.Email,
                    PhoneNumber = owner.Phone,
                    CompanyName = owner.CompanyName,
                    SignUpDate = owner.SignUpDate,
                    VenueName = _venueService.GetVenueNameById(owner.VenueId),
                    VenueId = owner.VenueId
                };
                return View(model);

            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int id)
        {
            //Bad request if value is 0
            if (id == 0) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            //Find venue owner using the id
            VenueOwner owner = _venueOwnerService.GetVenueOwnerById(id);

            //Initialize view model values using the owner values
            CreateVenueOwnerViewModel model = new CreateVenueOwnerViewModel()
            { 
                VenueOwnerId = owner.VenueOwnerId,
                FirstName = owner.FirstName,
                LastName = owner.LastName,
                Email = owner.Email,
                PhoneNumber = owner.Phone,
                CompanyName = owner.CompanyName,
                SignUpDate = owner.SignUpDate,
                VenueName = _venueService.GetVenueNameById(owner.VenueId)
            };

Capstone/PickUpSports/PickUpSports/Views/VenueOwner/ClaimVenue.cshtml
@model PickUpSports.Models.ViewModel.VenueOwnerController.ClaimVenueFormViewModel

@{
    ViewBag.Title = "Claim Venue";
}

@using (Html.BeginForm("ClaimVenue", "VenueOwner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="container">
        <div class="row">
            <div class="form-box">
                <h2>Claim @Model.VenueName</h2>
                @if (!ViewData.ModelState.IsValid)
                {
                    <div class="row">
                        <div class="col-md-12">
                            @Html.ValidationSummary(false, null, new {@class = "text-danger"})

                        </div>
                    </div>
                }
                
                @Html.HiddenFor(x => x.VenueId)
                @Html.HiddenFor(x => x.VenueName)

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <input type="text" class="form-control" placeholder="First Name" name="FirstName">
                        </div>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" placeholder="Last Name" name="LastName">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <input type="text" class="form-control" placeholder="Email Address" name="Email">
                        </div>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" placeholder="Phone Number" name="PhoneNumber" pattern="\(?\d{3}\)?-? *\d{3}-? *-?\d{4}">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-12">
                            <input type="text" class="form-control" placeholder="Company name (if different from venue name)" name="CompanyName">
                        </div>
                    </div>
                </div>

                <center>
                    <div class="form-group">
                        <div class="row">
                            <p>Please attach proof of ownership of this venue.</p>
                            <div class="col-sm-12">
                                <input type="file" class="form-control" name="Document" data-icon="false">
                            </div>
                        </div>
                    </div>

                </center>
                <div class="form-group">
                    <div class="row">

                        <center>
                            <button type="submit" class="btn btn-default">Submit Form</button>
                        </center>
                    </div>
                </div>

                @if (ViewBag.SubmitEmailSent != null && ViewBag.SubmitEmailSent)
                {
                    <div class="form-group">
                        <center>
                            <p><span class="glyphicon glyphicon-ok"></span> Your request has been sent!</p>
                            <p>Please allow 24-48 hours for an administrator to get back to you.</p>
                        </center>
                    </div>
                }
            </div>
        </div>
    </div>
}

Capstone/PickUpSports/PickUpSports/Views/VenueOwner/Create.cshtml
@model PickUpSports.Models.ViewModel.VenueOwnerController.CreateVenueOwnerViewModel

@{
    ViewBag.Title = "Initialize Your Information";
}

@using (Html.BeginForm("Create", "VenueOwner", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row">
            <div class="form-box">
                <h2>Initialize Venue Owner</h2>
                <br/>
                <form role="form" id="game-form">

                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-user"></span>
                            </div>
                            <input type="text" class="form-control" name="FirstName" placeholder="First Name">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-user"></span>
                            </div>
                            <input type="text" class="form-control" name="LastName" placeholder="Last Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-envelope"></span>
                            </div>
                            <input type="text" class="form-control" name="Email" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-earphone"></span>
                            </div>
                            <input type="text" class="form-control" name="PhoneNumber" placeholder="Phone Number">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-lock"></span>
                            </div>
                            <input type="text" class="form-control" name="CompanyName" placeholder="Company Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-globe"></span>
                            </div>
                            @Html.DropDownListFor(
                                x => x.VenueId,
                                new SelectList(ViewBag.Venues, "Key", "Value"),
                                "Select a Venue",
                                new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <center>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </center>
                    </div>
                </form>
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capstone/PickUpSports/PickUpSports/Views/VenueOwner/Detail.cshtml
@model PickUpSports.Models.ViewModel.VenueOwnerController.CreateVenueOwnerViewModel

@{
    ViewBag.Title = "Your Profile";
}

<div class="container">
    <div class="row">
        <div class="form-box">
            <h2>@Model.VenueName's Owner</h2>
            @if (ViewBag.IsOwner)
            {
                <div class="well">
                    <p>@Html.DisplayFor(x => x.FirstName) @Html.DisplayFor(x => x.LastName)</p>
                    <p>@Html.DisplayFor(x => x.Email)</p>
                    <p>@Html.DisplayFor(x => x.PhoneNumber)</p>
                    <p>
                        <center>
                            @Html.ActionLink("Edit Information", "Edit", new { id = Model.VenueOwnerId }) | @Html.ActionLink("Go To Venue Page", "Details", "Venue", new { id = Model.VenueId}, null)
                        </center>
                    </p>
                </div>
            }
            else
            {
                <div class="well">
                    <p>@Html.DisplayFor(x => x.FirstName) @Html.DisplayFor(x => x.LastName)</p>
                    <p>
                        <center>
                            <a href="#" data-toggle="modal" data-target="#confirm">Message Owner</a>
                        </center>
                    </p>

                </div>
            }
        </div>
    </div>
</div>

<div class="row" style="padding-top: 30px">
    @if (ViewBag.IsOwner)
    {
        <div id="calendar" style="margin: auto; width: 80%; border: 1px solid black; padding: 10px; background-color: #2F2D2E"></div>
             <div id="myModal" class="modal fade" role="dialog">
                 <div class="modal-dialog"> 
                     <div class="modal-content" style="background-color: #2F2D2E">
                         <div class="modal-header">
                             <button type="button" class="close" data-dismiss="modal">&times;</button>
                             <h5 class="modal-title"><span id="eventTitle"></span></h5>
                         </div>
                         <div class="modal-body">
                             <p id="pDetails"></p>
                         </div>
                         <div class="modal-footer">
                             <center>
                                 <button type="button" class="btn btn-default" id="submit" data-dismiss="modal">Close</button>
                             </center>
                             </div>
                     </div>
                 </div>
             </div>
    }

</div>
@using (Html.BeginForm("MessageOwner", "VenueOwner", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.VenueOwnerId)

    <!-- Modal -->
    <div class="modal fade" id="confirm" tabindex="-1" role="dialog" aria-labelledby="confirmRemove" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="background-color: #2F2D2E">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmRemove">New Message for @Model.FirstName @Model.LastName</h5>
                    <br />
                    @Html.LabelFor(x => x.MessageSubject)
                    @Html.EditorFor(x => x.MessageSubject, new { htmlAttributes = new { @class = "form-control", placeholder = "Subject" } })
                </div>
                <div class="modal-body">
                    @Html.LabelFor(x => x.MessageBody)
                    @Html.TextAreaFor(x => x.MessageBody, new { @class = "form-control", rows = 5, placeholder = "Questions, Comments, or Concerns" })
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-default" name="Button">Send Message</button>
                </div>
            </div>
        </div>
    </div>
}

<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css" rel="stylesheet" />
<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.print.css" rel="stylesheet" media="print" />

@section Scripts{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>

    <script>
        $(document).ready(function() {
            var events = [];
            $.ajax({
                type: "GET",
                url: "/VenueOwner/GetEvents/" + @Model.VenueId,
                success: function(data) {
                    $.each(data,
                        function(i, v) {
                            events.push({
                                title: v.Subject,
                                start: moment(v.Start),
                                end: v.End != null ? moment(v.End) : null,
                                gameStatus: v.GameStatus,
                                gameId: v.GameId,
                                color: v.Color,
                            });
                        });

                    GenerateCalendar(events);
                },
                error: function(error) {
                    alert('failed');
                }
            });

            function GenerateCalendar(events) {
                $('#calendar').fullCalendar('destroy');
                $('#calendar').fullCalendar({
                    contentHeight: 500,
                    defaultDate: new Date(),
                    timeFormat: 'h(:mm)a',
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month,basicWeek,basicDay,agenda'
                    },
                    dayRender: function(date, cell) {
                        var today = moment();
                        if (isSameDayAndMonth(today, date)) {
                            cell.css("background-color", "black");
                        }
                    },
                    eventLimit: true,
                    eventColor: '#378006',
                    events: events,
                    eventClick: function(calEvent, jsEvent, view) {
                        $('#myModal #eventTitle').text(calEvent.title);
                        var $description = $('<div/>');
                        $description.append($('<p/>')
                            .html('<b>Start:</b>' + " " + calEvent.start.format('MMMM Do YYYY, h:mm:ss a')));
                        if (calEvent.end != null) {
                            $description.append($('<p/>')
                                .html('<b>End:</b>' + " " + calEvent.end.format('MMMM Do YYYY, h:mm:ss a')));
                        }
                        $description.append($('<p/>').html('<b>Game status:</b>' + " " + calEvent.gameStatus));
                        console.log(calEvent.gameStatus);
                        if (calEvent.gameStatus === "Open" || calEvent.gameStatus === "Accepted") {
                            var rejectUrl = '@Url.Action("RejectGame", "VenueOwner", new {id = "-1"})';
                            rejectUrl = rejectUrl.replace("-1", calEvent.gameId);
                            var rejectTxt = "Reject Game";
                            $description.append($('<p/>').html('<center>' + rejectTxt.link(rejectUrl) + '</center>'));

                        } else {
                            var acceptUrl = '@Url.Action("AcceptGame", "VenueOwner", new {id = "-1"})';
                            acceptUrl = acceptUrl.replace("-1", calEvent.gameId);
                            var acceptTxt = "Reinstate Game";
                            $description.append($('<p/>').html('<center>' + acceptTxt.link(acceptUrl) + '</center>'));
                        }

                        $('#myModal #pDetails').empty().html($description);

                        $('#myModal').modal();
                    }
                });
            }

            function isSameDayAndMonth(m1, m2){
                return m1.date() === m2 .date() && m1.month() === m2.month()
            }

        })
    </script>
}

Capstone/PickUpSports/PickUpSports/Views/VenueOwner/Edit.cshtml
@model PickUpSports.Models.ViewModel.VenueOwnerController.CreateVenueOwnerViewModel

@{
    ViewBag.Title = "Edit Your Information";
}

@using (Html.BeginForm("Edit", "VenueOwner", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row">
            <div class="form-box">
                <h2>@ViewBag.Title</h2>
                <br/>
                <form role="form" id="game-form">
                    @Html.HiddenFor(x => x.VenueOwnerId)

                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-user"></span>
                            </div>
                            <input type="text" class="form-control" name="FirstName" value="@Model.FirstName" placeholder="First Name">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-user"></span>
                            </div>
                            <input type="text" class="form-control" name="LastName" value="@Model.LastName" placeholder="Last Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-envelope"></span>
                            </div>
                            <input type="text" class="form-control" name="Email" value="@Model.Email"placeholder="Email">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-earphone"></span>
                            </div>
                            <input type="text" class="form-control" name="PhoneNumber" value="@Model.PhoneNumber" placeholder="Phone Number">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-lock"></span>
                            </div>
                            <input type="text" class="form-control" name="CompanyName" value="@Model.CompanyName" placeholder="Company Name">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <span class="glyphicon glyphicon-globe"></span>
                            </div>
                            <input type="text" class="form-control" name="CompanyName" value="@Model.VenueName" placeholder="Company Name" readonly>
                        </div>
                    </div>
                    @if (!ViewData.ModelState.IsValid)
                    {
                        <div class="row">
                            <div class="col-md-12">
                                @Html.ValidationSummary(false, null, new {@class = "text-danger"})

                            </div>
                        </div>
                    }
                    <div class="form-group">
                        <center>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </center>
                    </div>
                </form>
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capstone/PickUpSports/PickUpSports/Views/VenueOwner/MessageOwner.cshtml
@{
    ViewBag.Title = "MessageOwner";
}

<h2>MessageOwner</h2>

Capstone/PickUpSports/PickUpSports/Views/VenueOwner/_ModifyVenueOwners.cshtml
@model List<PickUpSports.Models.ViewModel.VenueOwnerController.VenueOwnerViewModel>
    
<ul class="list-group">
    @foreach (var owner in Model)
    {
        <li class="list-group-item">
            <p>
                Venue: @Html.DisplayFor(x => owner.VenueName)
                <br />Owner: @Html.DisplayFor(x => owner.FirstName) @Html.DisplayFor(x => owner.LastName)
                <br />Email: @Html.DisplayFor(x => owner.Email)
                <br />Phone: @Html.DisplayFor(x => owner.PhoneNumber)
            </p>

            @Html.ActionLink("Edit", "Edit", "VenueOwner", new { id = owner.VenueOwnerId }, null)
        </li>
    }
</ul>

@Html.ActionLink("Add New Venue Owner", "Create", "VenueOwner", null, null)