Capstone/PickUpSports/PickUpSports/Models/DatabaseModels/SportPreference.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PickUpSports.Models.DatabaseModels
{
    public class SportPreference
    {
        public int SportPrefID { get; set; }
        public int ContactID { get; set; }
        public int SportID { get; set; }
    }
}

Capstone/PickUpSports/PickUpSports/Models/ViewModel/ContactController/SportPreferenceViewModel.cs
using System.Collections.Generic;

namespace PickUpSports.Models.ViewModel.ContactController
{
    public class SportPreferenceViewModel
    {
        public int ContactId { get; set; }
        public List<string> SportName { get; set; }
        public bool IsPublicProfileView { get; set; }
    }
}

Capstone/PickUpSports/PickUpSports/Controllers/SportPreferencesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PickUpSports.DAL;
using PickUpSports.Models.DatabaseModels;
using PickUpSports.Models.ViewModel.ContactController;

namespace PickUpSports.Controllers
{
    public class SportPreferencesController : Controller
    {
        private readonly PickUpContext _context;

        public SportPreferencesController(PickUpContext context)
        {
            _context = context;
        }        

        [HttpGet]
        public ActionResult ModifySportPreferences()
        {
            //Identify the person using email
            string newContactEmail = User.Identity.GetUserName();

            //find the contact
            Contact contact = _context.Contacts.FirstOrDefault(x => x.Email == newContactEmail);

            // Create view model 
            var model = new CreateSportPreferenceViewModel
            {
                ContactId = contact.ContactId,
                ContactUsername = contact.Username,
                SportPreferenceCheckboxes = new List<SelectSportPreferenceViewModel>()
            };

            List<Sport> sports = _context.Sports.ToList();

            // For each sport in the database, add an object to the Sport Preferences list
            // in the view model which will translate to checkboxes on the view
            foreach (var sport in sports)
            {
                // Initialize viewmodel that will be used for checkbox
                SelectSportPreferenceViewModel sportPrefCheckbox = new SelectSportPreferenceViewModel
                {
                    SportId = sport.SportID,
                    SportName = sport.SportName
                };

                // Check if user has preference set for this specific sport
                SportPreference sportPref = _context.SportPreferences.FirstOrDefault(s => s.ContactID == contact.ContactId && s.SportID == sport.SportID);

                // If no preference for sport, set IsSelected to false because it's not a preference for this user
                if (sportPref == null) sportPrefCheckbox.IsSelected = false;
                else sportPrefCheckbox.IsSelected = true;

                // Add to list of checkboxes
                model.SportPreferenceCheckboxes.Add(sportPrefCheckbox);

            }
            return View(model);
        }

        [HttpPost]
        public ActionResult ModifySportPreferences(CreateSportPreferenceViewModel model)
        {
            // Update database with any updated values from checkboxes
            foreach (var preference in model.SportPreferenceCheckboxes)
            {
                // check for existing sport preference
                SportPreference existing = _context.SportPreferences.FirstOrDefault(s => s.ContactID == model.ContactId && s.SportID == preference.SportId);

                // Sport preference does not exist and user has selected it so add to database
                if (existing == null && preference.IsSelected)
                {
                    _context.SportPreferences.Add(new SportPreference
                    {
                        ContactID = model.ContactId,
                        SportID = preference.SportId
                    });
                }

                // Sport preference exists but user no longer wants it to be set so remove
                if (existing != null && !preference.IsSelected)
                {
                    _context.SportPreferences.Remove(existing);
                }

                _context.SaveChanges();
            }

            return RedirectToAction("Details", "Contact");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Capstone/PickUpSports/PickUpSports/Views/SportPreferences/Delete.cshtml
@model PickUpSports.Models.DatabaseModels.SportPreference

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SportPreference</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ContactID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SportID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SportID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Profile", "Index")
        </div>
    }
</div>

Capstone/PickUpSports/PickUpSports/Views/SportPreferences/Edit.cshtml
@model PickUpSports.Models.DatabaseModels.SportPreference

@{
    ViewBag.Title = "Edit Sport Preferences";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit Sport Preferences</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SportPrefID)

        <div class="form-group">
            @Html.LabelFor(model => model.ContactID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SportID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SportID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SportID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capstone/PickUpSports/PickUpSports/Views/SportPreferences/ModifySportPreferences.cshtml
@model PickUpSports.Models.ViewModel.ContactController.CreateSportPreferenceViewModel

@{
    ViewBag.Title = "Add Your Sport Preferences";
}

@using (Html.BeginForm("ModifySportPreferences", "SportPreferences", FormMethod.Post))
{
    <div class="container">
        <div class="row">
            <div class="form-box">
                <h4>@Model.ContactUsername's Sport Preferences</h4>
                <div class="well">
                    @Html.HiddenFor(model => model.ContactId)

                    @for (var i = 0; i < Model.SportPreferenceCheckboxes.Count; i++)
                    {
                        <div class="row">
                            <div class="form-group col-md-12">
                                @Html.CheckBoxFor(x => Model.SportPreferenceCheckboxes[i].IsSelected) @Html.DisplayFor(x => Model.SportPreferenceCheckboxes[i].SportName)
                            </div>

                        </div>
                        @Html.HiddenFor(x => Model.SportPreferenceCheckboxes[i].IsSelected)
                        @Html.HiddenFor(x => Model.SportPreferenceCheckboxes[i].SportId)
                    }

                    <div class="row">
                        <center>
                            <button type="submit" id="submit" class="btn btn-default">Save Changes</button>
                        </center>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Capstone/PickUpSports/PickUpSports/Views/SportPreferences/_SportPreferences.cshtml
@model PickUpSports.Models.ViewModel.ContactController.SportPreferenceViewModel

@Html.HiddenFor(x => x.ContactId)
@if (Model.SportName != null && Model.SportName.Count > 0) 
{
    <ul class="list-group">
        @foreach (var sport in Model.SportName)
        {
            <li class="list-group-item"><center>@Html.DisplayFor(x => sport)</center></li>

        }
    </ul>
}
else
{
    if (Model.IsPublicProfileView)
    {
        <h6>This user doesn't have any sport preferences set yet.</h6>
    }
    else
    {
        <h6>You do not have any sport preferences set yet.</h6>
    }
}

@if (!Model.IsPublicProfileView)
{
    <center>@Html.ActionLink("Edit", "ModifySportPreferences", "SportPreferences")</center>
}